[package]
name = "crusty"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-complex = "0.4"
assert_approx_eq = "1.1.0"
nalgebra = "0.31.4"

[[bin]]
name = "three_body"
test = false
bench = false